"""Initial migration: create all tables

Revision ID: 9472af43883e
Revises: 
Create Date: 2026-06-04 12:12:31.099818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9472af43883e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_guru', sa.String(length=20), nullable=False),
    sa.Column('nama_guru', sa.String(length=100), nullable=False),
    sa.Column('mata_pelajaran', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_guru')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kelas', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_siswa_kelas', 'siswa', ['kelas'], unique=False)
    op.create_index('ix_siswa_nis', 'siswa', ['nis'], unique=True)

    op.create_table('nilai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('mata_pelajaran', sa.String(length=100), nullable=False),
    sa.Column('nilai_tugas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nilai_uts', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nilai_uas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nilai_akhir', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status_lulus', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guru_id'], ['guru.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siswa_id', 'mata_pelajaran', name='uq_siswa_mapel')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('siswa_id', sa.Integer(), nullable=True),
    sa.Column('guru_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guru_id'], ['guru.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_index('ix_users_username', 'users')
    op.drop_table('users')
    op.drop_table('nilai')
    op.drop_index('ix_siswa_nis', 'siswa')
    op.drop_index('ix_siswa_kelas', 'siswa')
    op.drop_table('siswa')
    op.drop_table('guru')
    # ### end Alembic commands ###
